=== Chloe-Larsen/IMY-210-Project/schedule.xsd
<!--Larsen u25004141-->
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="schedule">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="COS210" type="course" minOccurs="0"/>
                <xs:element name="COS212" type="course" minOccurs="0"/>
                <xs:element name="COS216" type="course" minOccurs="0"/>
                <xs:element name="COS221" type="course" minOccurs="0"/>
                <xs:element name="INF272" type="course" minOccurs="0"/>
                <xs:element name="IMY210" type="course" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="course">
        <xs:sequence>
            <xs:element name="Code" type="CourseCodeType"/>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Semester" type="SemesterType"/>
            <xs:element name="Lectures" type="LecturesType"/>
            <xs:element name="Tutorials" type="TutorialsType" minOccurs="0"/>
            <xs:element name="Practicals" type="PracticalsType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="CourseCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3} [0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SemesterType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="S1"/>
            <xs:enumeration value="Y"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="LecturesType">
        <xs:sequence>
            <xs:element name="L1" type="SessionType"/>
            <xs:element name="L2" type="SessionType" minOccurs="0"/>
            <xs:element name="L3" type="SessionType" minOccurs="0"/>
            <xs:element name="L4" type="SessionType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TutorialsType">
        <xs:sequence>
            <xs:element name="T1" type="SessionType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PracticalsType">
        <xs:sequence>
            <xs:element name="P1" type="SessionType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SessionType">
        <xs:sequence>
            <xs:element name="Day" type="DayType"/>
            <xs:element name="Time" type="TimeType"/>
            <xs:element name="Venue" type="VenueType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="DayType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Monday"/>
            <xs:enumeration value="Tuesday"/>
            <xs:enumeration value="Wednesday"/>
            <xs:enumeration value="Thursday"/>
            <xs:enumeration value="Friday"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TimeType">
        <xs:sequence>
            <xs:element name="StartTime" type="Time"/>
            <xs:element name="EndTime" type="Time"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Time">
        <xs:restriction base="xs:string">
            <xs:pattern value="([01][0-9]|2[0-3]):[0-5][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="VenueType">
        <xs:sequence>
            <xs:element name="Campus" type="xs:string"/>
            <xs:element name="Building" type="xs:string"/>
            <xs:element name="Room" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Chloe-Larsen/IMY-210-Project/schedule.xml
<!--Larsen u25004141-->
<?xml version="1.0" encoding="UTF-8" ?>
<schedule 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schedule.xsd">
    <COS210>
        <Code>COS 210</Code>
        <Name>Theoretical computer science</Name>
        <Semester>S1</Semester>
        <Lectures>
            <L1>
                <Day>Monday</Day>
                <Time>
                    <StartTime>11:30</StartTime>
                    <EndTime>12:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>2-26</Room>
                </Venue>
            </L1>
            <L2>
                <Day>Wednesday</Day>
                <Time>
                    <StartTime>08:30</StartTime>
                    <EndTime>09:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>2-26</Room>
                </Venue>
            </L2>
        </Lectures>
        <Tutorials>
            <T1>
                <Day>Friday</Day>
                <Time>
                    <StartTime>14:30</StartTime>
                    <EndTime>15:30</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>2-26</Room>
                </Venue>
            </T1>
        </Tutorials>
    </COS210>
    <COS212>
        <Code>COS 212</Code>
        <Name>Data structures and algorithms</Name>
        <Semester>S1</Semester>
        <Lectures>
            <L1>
                <Day>Monday</Day>
                <Time>
                    <StartTime>16:30</StartTime>
                    <EndTime>17:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>Chemistry Building</Building>
                    <Room>Large Chemistry Hall</Room>
                </Venue>
            </L1>
            <L2>
                <Day>Wednesday</Day>
                <Time>
                    <StartTime>09:30</StartTime>
                    <EndTime>10:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>Chancellor's Building</Building>
                    <Room>Louw hall</Room>
                </Venue>
            </L2>
            <L3>
                <Day>Thursday</Day>
                <Time>
                    <StartTime>16:30</StartTime>
                    <EndTime>17:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>Chancellor's Building</Building>
                    <Room>Roos hall</Room>
                </Venue>
            </L3>
        </Lectures>
        <Tutorials>
            <T1>
                <Day>Friday</Day>
                <Time>
                    <StartTime>09:30</StartTime>
                    <EndTime>10:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>Chancellor's Building</Building>
                    <Room>Louw hall</Room>
                </Venue>
            </T1>
        </Tutorials>
        <Practicals>
            <P1>
                <Day>Tuesday</Day>
                <Time>
                    <StartTime>09:30</StartTime>
                    <EndTime>12:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>Informatorium</Building>
                    <Room>Purple Lab</Room>
                </Venue>
            </P1>
        </Practicals>
    </COS212>
    <COS216>
       <Code>COS 216</Code>
        <Name>Netcentric computer systems</Name>
        <Semester>S1</Semester>
        <Lectures>
            <L1>
                <Day>Monday</Day>
                <Time>
                    <StartTime>08:30</StartTime>
                    <EndTime>09:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>2-23</Room>
                </Venue>
            </L1>
            <L2>
                <Day>Tuesday</Day>
                <Time>
                    <StartTime>12:30</StartTime>
                   <EndTime>13:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>4-4</Room>
                </Venue>
            </L2>
            <L3>
                <Day>Wednesday</Day>
                <Time>
                    <StartTime>10:30</StartTime>
                    <EndTime>11:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>4-4</Room>
                </Venue>
            </L3>
            <L4>
                <Day>Thursday</Day>
                <Time>
                    <StartTime>09:30</StartTime>
                    <EndTime>10:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>4-4</Room>
                </Venue>
            </L4>
        </Lectures>
        <Practicals>
            <P1>
                <Day>Monday</Day>
                <Time>
                    <StartTime>13:30</StartTime>
                    <EndTime>16:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>Informatorium</Building>
                    <Room>Maroon Lab</Room>
                </Venue>
            </P1>
        </Practicals>
    </COS216>
    <COS221>
        <Code>COS 221</Code>
        <Name>Introduction to database systems </Name>
        <Semester>S1</Semester>
        <Lectures>
            <L1>
                <Day>Monday</Day>
                <Time>
                    <StartTime>09:30</StartTime>
                    <EndTime>10:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>2-26</Room>
                </Venue>
            </L1>
            <L2>
                <Day>Wednesday</Day>
                <Time>
                    <StartTime>07:30</StartTime>
                    <EndTime>08:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>2-26</Room>
                </Venue>
            </L2>
            <L3>
                <Day>Thursday</Day>
                <Time>
                    <StartTime>11:30</StartTime>
                    <EndTime>12:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>4-4</Room>
                </Venue>
            </L3>
            <L4>
                <Day>Friday</Day>
                <Time>
                    <StartTime>10:30</StartTime>
                    <EndTime>11:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>4-4</Room>
                </Venue>
            </L4>
        </Lectures>
        <Practicals>
            <P1>
                <Day>Wednesday</Day>
                <Time>
                    <StartTime>11:30</StartTime>
                    <EndTime>14:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>Informatorium</Building>
                    <Room>Blue Lab</Room>
                </Venue>
            </P1>
        </Practicals>
    </COS221>
    <INF272>
        <Code>INF 272</Code>
        <Name>Informatics</Name>
        <Semester>Y</Semester>
        <Lectures>
             <L1>
               <Day>Monday</Day>
                <Time>
                     <StartTime>12:30</StartTime>
                    <EndTime>13:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>4-4</Room>
                </Venue>
            </L1>
        </Lectures>
       <Practicals>
            <P1>
                 <Day>Tuesday</Day>
                <Time>
                   <StartTime>14:30</StartTime>
                    <EndTime>16:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>Informatorium</Building>
                    <Room>Brown Lab</Room>
                </Venue>
            </P1>
        </Practicals>
    </INF272>
    <IMY210>
        <Code>IMY 210</Code>
        <Name>Advanced web technologies 1</Name>
        <Semester>S1</Semester>
        <Lectures>
            <L1>
                <Day>Wednesday</Day>
                <Time>
                    <StartTime>14:30</StartTime>
                    <EndTime>15:20</EndTime>
                </Time>
                <Venue>
                    <Campus>Hatfield</Campus>
                    <Building>IT</Building>
                    <Room>4-2</Room>
                </Venue>
            </L1>
            <L2>
                <Day>Friday</Day>
                <Time>
                    <StartTime>08:30</StartTime>
                    <EndTime>09:20</EndTime>
                </Time>
                <Venue>
